'use client'

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui'
import { 
  Users, 
  UserCheck, 
  UserX, 
  DollarSign, 
  TrendingUp,
  Award 
} from 'lucide-react'
import type { Database } from '@/types/database.types'

type StaffProfile = Database['public']['Tables']['staff_profiles']['Row']
type Profile = Database['public']['Tables']['profiles']['Row']

type StaffMember = StaffProfile & {
  profiles?: Profile | null
  appointments_count?: number
  revenue_generated?: number
  average_rating?: number
}

interface StaffStatsProps {
  staff: StaffMember[]
}

export function StaffStats({ staff }: StaffStatsProps) {
  const totalStaff = staff.length
  const activeStaff = staff.filter(s => s.is_active).length
  const inactiveStaff = totalStaff - activeStaff
  
  const totalRevenue = staff.reduce((sum, s) => sum + (s.revenue_generated || 0), 0)
  const avgRevenue = totalStaff > 0 ? totalRevenue / totalStaff : 0
  
  const totalAppointments = staff.reduce((sum, s) => sum + (s.appointments_count || 0), 0)
  
  const staffWithRatings = staff.filter(s => s.average_rating && s.average_rating > 0)
  const avgRating = staffWithRatings.length > 0 
    ? staffWithRatings.reduce((sum, s) => sum + (s.average_rating || 0), 0) / staffWithRatings.length
    : 0

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount)
  }

  const stats = [
    {
      title: 'Total Staff',
      value: totalStaff.toString(),
      description: 'All staff members',
      icon: Users,
      color: 'text-blue-600'
    },
    {
      title: 'Active Staff',
      value: activeStaff.toString(),
      description: 'Currently active',
      icon: UserCheck,
      color: 'text-green-600'
    },
    {
      title: 'Inactive Staff',
      value: inactiveStaff.toString(),
      description: 'Currently inactive',
      icon: UserX,
      color: 'text-red-600'
    },
    {
      title: 'Total Revenue',
      value: formatCurrency(totalRevenue),
      description: 'Generated by all staff',
      icon: DollarSign,
      color: 'text-green-600'
    },
    {
      title: 'Avg Revenue',
      value: formatCurrency(avgRevenue),
      description: 'Per staff member',
      icon: TrendingUp,
      color: 'text-blue-600'
    },
    {
      title: 'Avg Rating',
      value: avgRating > 0 ? avgRating.toFixed(1) : 'N/A',
      description: `${totalAppointments} total appointments`,
      icon: Award,
      color: 'text-yellow-600'
    }
  ]

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {stats.map((stat) => {
        const Icon = stat.icon
        return (
          <Card key={stat.title}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">{stat.title}</CardTitle>
              <Icon className={`h-4 w-4 ${stat.color}`} />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stat.value}</div>
              <CardDescription>{stat.description}</CardDescription>
            </CardContent>
          </Card>
        )
      })}
    </div>
  )
}