import type { NavigationItem } from "./navigation.types";

export const salonOwnerNavigation: NavigationItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    href: "/dashboard",
    icon: "home",
  },
  {
    id: "separator-business",
    label: "Business Management",
    href: "#",
    icon: "",
    type: "separator",
  },
  {
    id: "appointments",
    label: "Appointments",
    href: "/dashboard/appointments",
    icon: "calendar",
  },
  {
    id: "customers",
    label: "Customers",
    href: "/dashboard/customers",
    icon: "users",
  },
  {
    id: "staff",
    label: "Staff",
    href: "/dashboard/staff",
    icon: "userCheck",
  },
  {
    id: "services",
    label: "Services",
    href: "/dashboard/services",
    icon: "scissors",
  },
  {
    id: "separator-operations",
    label: "Operations",
    href: "#",
    icon: "",
    type: "separator",
  },
  {
    id: "schedules",
    label: "Staff Schedules",
    href: "/dashboard/staff-schedules",
    icon: "clock",
  },
  {
    id: "inventory",
    label: "Inventory",
    href: "/dashboard/inventory",
    icon: "package",
  },
  {
    id: "locations",
    label: "Locations",
    href: "/dashboard/locations",
    icon: "briefcase",
  },
  {
    id: "separator-growth",
    label: "Growth & Analytics",
    href: "#",
    icon: "",
    type: "separator",
  },
  {
    id: "analytics",
    label: "Analytics",
    href: "/dashboard/analytics",
    icon: "chart",
  },
  {
    id: "revenue",
    label: "Revenue",
    href: "/dashboard/revenue",
    icon: "dollar",
  },
  {
    id: "reviews",
    label: "Reviews",
    href: "/dashboard/reviews",
    icon: "star",
  },
  {
    id: "campaigns",
    label: "Marketing",
    href: "/dashboard/campaigns",
    icon: "message",
  },
  {
    id: "reports",
    label: "Reports",
    href: "/dashboard/reports",
    icon: "file",
  },
  {
    id: "separator-settings",
    label: "Configuration",
    href: "#",
    icon: "",
    type: "separator",
  },
  {
    id: "settings",
    label: "Settings",
    href: "/dashboard/settings",
    icon: "settings",
  },
  {
    id: "team",
    label: "Team Members",
    href: "/dashboard/team-members",
    icon: "userCheck",
  },
];
